# Generated by Django 4.2.28 on 2026-03-16 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_profiles', '0002_add_influencer_payout_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='influencerprofile',
            name='avg_views_per_reel',
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='follower_age_ratio',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"13-17": 5, "18-24": 45, "25-34": 30}', null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='instagram_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='follower_gender_ratio',
            field=models.JSONField(blank=True, default=dict, help_text='e.g., {"male": 60, "female": 40}'),
        ),
        migrations.AlterField(
            model_name='influencerprofile',
            name='top_audience_locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
