# Generated by Django 4.2.28 on 2026-03-25 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_profiles', '0004_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='gstin',
            field=models.CharField(blank=True, help_text='15-digit GST Number', max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Legal Entity Name retrieved from GSTN', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
