# Generated by Django 4.2.28 on 2026-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_profiles', '0006_alter_contract_status_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('work_submitted', 'Work Submitted'), ('work_verified', 'Work Verified'), ('payment_done', 'Payment Done'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
