# Generated by Django 4.2.28 on 2026-05-07 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_profiles', '0007_customuser_profile_picture_alter_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='completion_deadline',
            field=models.DateTimeField(blank=True, help_text='Agreed deadline to complete the work', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='24h deadline for business to confirm escrow; None if no escrow', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='escrow_opted',
            field=models.BooleanField(default=False, help_text='True if influencer chose escrow protection on this contract'),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='custom_category',
            field=models.CharField(blank=True, default='', help_text='Raw user-typed category before word-match normalisation', max_length=200),
        ),
        migrations.AddField(
            model_name='influencerprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='Set to True once influencer agrees to T&C'),
        ),
        migrations.CreateModel(
            name='CampaignInterest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, default='', help_text='Optional pitch note from the influencer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(db_column='campaign_id', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='users_and_profiles.campaign')),
                ('influencer', models.ForeignKey(db_column='influencer_id', on_delete=django.db.models.deletion.CASCADE, related_name='campaign_interests', to='users_and_profiles.influencerprofile')),
            ],
            options={
                'db_table': 'campaign_interests',
                'ordering': ['-created_at'],
                'unique_together': {('campaign', 'influencer')},
            },
        ),
    ]
